spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auctart?serverTimezone=UTC
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/auctart?serverTimezone=UTC
    user: root
    password: password
    schemas: auctart
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
      enabled: true

security:
  jwt:
    secret: asdfg
