spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auctart?serverTimezone=UTC
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/auctart?serverTimezone=UTC
    user: root
    password: password
    schemas: auctart
    baseline-on-migrate: true

security:
  jwt:
    secret: asdfg